version: '3.8'

services:
  frontend:
    build: ./Frontend
    container_name: frontend_portafolio   
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0

